Require newer h11
The test suite currently doesn't run with older h11:

```
==================================== ERRORS ====================================
_____________________ ERROR collecting test/test_server.py _____________________
test/test_server.py:289: in <module>
    ) -> List[h11.Event]:
E   AttributeError: module 'h11' has no attribute 'Event'
```

Although `h11.Event` is only used in the test suite, I think we shouldn't declare support for versions we cannot test with.